version: '3.6'
services:

  backend:
    image: treecloud/bccelsalvador:latest
    command: python manage.py runserver 0.0.0.0:8000
    build:
      context: ./invitations/
      dockerfile: Dockerfile
    volumes:
      - app:/app
    ports:
      - "8000:8000"
    networks:
      - bccelsalvador
    depends_on:
      - db
    links:
      - db
    environment:
      env_file: /run/secrets/bccelsalvador
    secrets:
      - bccelsalvador
    volumes:
      - static:/app/static

  nginx:
      image: treecloud/nginx
      restart: always
      build: ./nginx/
      volumes: 
      - logs:/app/logs
      - app:/app/invitations/static
      ports: 
        - "3030:80"
      depends_on:
        - backend
      networks:
        - bccelsalvador

  db:
    image: postgres:11
    volumes:
    - data_bcc:/var/lib/postgresql/data
    ports:
    - 6543:5432
    networks:
      - bccelsalvador
    environment:
      POSTGRES_DB: invitation-qr
      POSTGRES_USER: postgres

  web:
    image: teecloud/web:latest
    restart: always
    build: ./nginx/
    volumes:
      - ./nginx/:/etc/nginx/conf.d
      - ./logs/:/app/logs
      - static:/app/static
    ports:
      - "5050:80"
    networks:
      - bccelsalvador

networks:
  bccelsalvador:
    driver: overlay

volumes:
  data_bcc:
    driver: local
  logs:
    driver: local
  static:

secrets:
  bccelsalvador:
    external: true
  bcc-postgres:
    external: true
