# Generated by Django 2.2 on 2019-11-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_participante', models.CharField(max_length=255, unique=True, verbose_name='Código de participante')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del participante')),
                ('empresa', models.CharField(max_length=255, verbose_name='Empresa (Razón social)')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono')),
                ('f_name', models.CharField(max_length=255, verbose_name='Facturar a nombre de')),
                ('nit', models.CharField(max_length=17, verbose_name='NIT')),
                ('nrc', models.CharField(max_length=10, verbose_name='NRC')),
                ('orden_compra', models.CharField(blank=True, max_length=255, null=True, verbose_name='Orden de compra No.')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
    ]
