# Generated by Django 2.2 on 2019-11-08 23:00

from django.db import migrations, models
import landing.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_participante_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='qr_code',
            field=models.CharField(default=landing.models.createHash, max_length=100000, unique=True),
        ),
    ]
