# Generated by Django 2.2 on 2019-11-08 23:09

from django.db import migrations, models
import landing.models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_participante_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='qr_code',
        ),
        migrations.AlterField(
            model_name='participante',
            name='codigo_participante',
            field=models.TextField(default=landing.models.createHash, unique=True, verbose_name='Código de participante'),
        ),
    ]
