# Generated by Django 2.2 on 2019-11-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_asistente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistente',
            old_name='id_participante',
            new_name='participante',
        ),
    ]
