# Generated by Django 2.2 on 2019-11-08 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_auto_20191108_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='participante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='landing.Participante', verbose_name='participante'),
        ),
    ]
